### ISSUE TITLE
Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by jaimz22** [GulpFiction/gulpfiction#11]
first off, awesome utility!

I started to try to put together a little gulpfile, however the search npm wouldn't work! so I popped open my console and saw:

XMLHttpRequest cannot load http://registry.gulpjs.com/_count?q=keywords:gulpplugin,gulpfriendly. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://gulpfiction.divshot.io' is therefore not allowed access.

so... yeah that's not good!

**Comment by damienklinnert** [comment]
Hey @jaimz22 thanks for reporting the issue - I just had a quick looks and the registry doesn't exist anymore - this is why you get that error - would you mind trying to use the public nom registry instead?

**Comment by damienklinnert** [comment]
Hey @jaimz22 just deployed the fix. Thanks for reporting.
