### ISSUE TITLE
http://gulpfiction.divshot.io/ is not looking anymore for npm plugins

### ISSUE THREAD

**Issue by KvdM** [GulpFiction/gulpfiction#12]
Search for npm plugins isn't working anymore at http://gulpfiction.divshot.io/.

**Comment by damienklinnert** [comment]
Hey @KvdM thanks for reporting the issue! The search is clearly broken, looks like the endpoint doesn't exist anymore. I'd really appreciate your help on this if you find some time. You should be able to query the public npm registry.

Let me know if you could help that project with a fix.

**Comment by damienklinnert** [comment]
Hey @KvdM just deployed the fix. Thanks for reporting.
